version: '3.8'

services:
  sd-host:
    build: .
    container_name: sd-host
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./output:/app/output
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config/config.yml:/app/config/config.yml
    environment:
      - PYTHONPATH=/app/src
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
