# SD-Host Configuration
# Copy this file to config.yml and modify according to your needs

# Server configuration
server:
  host: "0.0.0.0"
  port: 8000
  debug: false
  workers: 1
  reload: false

# Stable Diffusion configuration
stable_diffusion:
  # Model configuration
  model_name: "runwayml/stable-diffusion-v1-5"
  model_path: "./models/stable-diffusion-v1-5"
  
  # Device configuration
  device: "auto"  # auto, cuda, cpu
  device_id: 0    # GPU device ID (for multi-GPU systems)
  
  # Performance settings
  precision: "fp16"  # fp16, fp32
  attention_slicing: true
  memory_efficient_attention: true
  cpu_offload: false
  
  # Generation defaults
  default_width: 512
  default_height: 512
  default_steps: 20
  default_cfg_scale: 7.5
  default_sampler: "DPMSolverMultistepScheduler"
  
  # Safety settings
  safety_checker: true
  nsfw_filter: true

# Storage configuration
storage:
  # Output directory for generated images
  output_dir: "./output"
  
  # Database configuration
  database_url: "sqlite+aiosqlite:///./data/sd_host.db"
  
  # Image retention settings
  max_images: 1000
  cleanup_interval: 3600  # seconds
  image_retention_days: 7

# API configuration
api:
  # Rate limiting
  rate_limit_requests: 10
  rate_limit_window: 60  # seconds
  
  # Request timeout
  timeout: 300  # seconds
  
  # Maximum request size
  max_request_size: 10485760  # 10MB
  
  # CORS settings
  cors_origins: ["*"]
  cors_methods: ["GET", "POST"]
  cors_headers: ["*"]

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "structured"  # structured, simple
  file: "./logs/sd_host.log"
  max_size: 10485760  # 10MB
  backup_count: 5

# Security configuration
security:
  # API key authentication (optional)
  api_key_enabled: false
  api_key: ""
  
  # HTTPS settings
  ssl_enabled: false
  ssl_cert_file: ""
  ssl_key_file: ""

# Monitoring configuration
monitoring:
  # Health check endpoint
  health_check_enabled: true
  
  # Metrics collection
  metrics_enabled: false
  metrics_endpoint: "/metrics"
  
  # Performance monitoring
  track_performance: true
